source "https://rubygems.org"

# Specify the version of Ruby
#ruby "3..2"

# Use GitHub Pages gem (it includes Jekyll and other plugins supported by GitHub Pages)
#gem "github-pages", group: :jekyll_plugins

# Add any additional plugins you might need
gem "jekyll-feed", "~> 0.15"
gem "jekyll-seo-tag", "~> 2.8"
